### ISSUE TITLE
Georgia 2023 Individual Income Tax Parameter Updates

### ISSUE THREAD

**Issue by Kevintowne** [PolicyEngine/policyengine-us#3732] opened 2024-01-29 19:09 UTC
According to the Form 500 and 500EZ, Georgia Individual Income Tax Booklet, 2023 Version, there're some parameter updates.

Reference: https://dor.georgia.gov/it-511-individual-income-tax-booklet

**Comment by PavelMakarchuk** [comment] 2024-06-21 13:29
Duplicate of #3895

**Closed by PavelMakarchuk** 2024-06-21 13:29 UTC
Labels: states/ga
