### ISSUE TITLE
`age` class is type `float` instead of `int`

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-us#3535] opened 2023-12-27 00:54 UTC
# Variable to amend: age

The `age` variable is coded as a `float` instead of an `int`, making it a bit challenging on the front end to limit input for this parameter to non-decimal values. This is also in contradiction with `core`, which has its own `age` class of type `int`.

**Comment by MaxGhenis** [comment] 2023-12-27 01:02
Duplicate of #3357

**Closed by MaxGhenis** 2023-12-27 01:02 UTC
