### ISSUE TITLE
Docs not building within Ubuntu test portion of GitHub Actions

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-us#4937] opened 2024-08-22 03:41 UTC
E.g., in this action run: https://github.com/PolicyEngine/policyengine-us/actions/runs/10499605400/job/29086674675. It would appear that deployment isn't failing as a result of this, but it would be good to clear up this error.

**Comment by MaxGhenis** [comment] 2024-08-22 03:46
Duplicate of #4761

**Closed by MaxGhenis** 2024-08-22 03:46 UTC
