### ISSUE TITLE
Remove CPS_2023

### ISSUE THREAD

**Issue by YichunRen** [PolicyEngine/policyengine-us#4088] opened 2024-03-06 04:30 UTC
https://github.com/PolicyEngine/policyengine-us/pull/4030 will remove EnhancedCPS_2023 in favor of EnhancedCPS_2022. Let's do the same for CPS_2023, reflecting a dataset's survey year as its name.

**Comment by MaxGhenis** [comment] 2024-03-06 17:39
Duplicate of #4032

**Closed by MaxGhenis** 2024-03-06 17:39 UTC
