### ISSUE TITLE
Switch to `pyproject.toml` with support for editable installations

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-us#4974] opened 2024-08-30 13:38 UTC
Received this warning on install:

`
DEPRECATION: Legacy editable install of policyengine-us==1.50.0 from file:///Users/administrator/Documents/PolicyEngine/policyengine-us (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
`

It looks like I was also forced by pip to install v.1.50.0 in order to support local editable mode. This was on Python 3.10.

**Comment by MaxGhenis** [comment] 2024-08-30 14:19
Duplicate of #4948

**Closed by MaxGhenis** 2024-08-30 14:19 UTC
