### ISSUE TITLE
GitHub error when building documentation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2040] opened 2023-03-29 23:36 UTC
The CPS-creation errors are now gone thanks to PR #2031, but the documentation build is now failing on GitHub:

<img width="1179" alt="Screenshot 2023-03-29 at 7 33 05 PM" src="https://user-images.githubusercontent.com/12170745/228690890-a2ef58ca-589a-4389-b04f-27b7720b3138.png">

**Comment by MaxGhenis** [comment] 2023-03-29 23:51
Fixed now (duplicate of #2038)

**Closed by MaxGhenis** 2023-03-29 23:51 UTC
Labels: bug, documentation
