### ISSUE TITLE
LA-EITC

### ISSUE THREAD

**Issue by Lodestone46** [PolicyEngine/policyengine-us#2068] opened 2023-04-03 17:25 UTC
EITC
5% of federal
https://revenue.louisiana.gov/TaxForms/IT540iWEB(2022)D1.pdf#page=15 
https://www.legis.la.gov/legis/Law.aspx?d=453085

**Comment by martinholmer** [comment] 2023-10-21 18:25
Duplicate of issue #2035.

**Closed by martinholmer** 2023-10-21 18:25 UTC
Labels: states/la
