### ISSUE TITLE
Ohio Lump Sum Retirement Credit

### ISSUE THREAD

**Issue by ThapeloMasasa** [PolicyEngine/policyengine-us#3285] opened 2023-11-20 06:24 UTC
Ohio Lump Sum Retirement Credit

Reference:
https://tax.ohio.gov/static/forms/ohio_individual/individual/2021/pit-it1040-booklet.pdf#page=30

**Comment by MaxGhenis** [comment] 2023-11-20 14:47
Duplicate of #2958

**Closed by MaxGhenis** 2023-11-20 14:47 UTC
