### ISSUE TITLE
Update HCUA for SNAP (Colorado)

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-us#4649] opened 2024-06-14 17:44 UTC
Update utility allowance in Colorado SNAP calculations so that all SNAP households will get the HCUA. Change will be effective October 1, 2024 (concurrently with regular SNAP income, allowances, and allotment updates).

Context: Later this year, the SNAP utility calculations are changing in a way that will increase a HH's utility allowance and thereby decrease countable income. Consistent with federal regulations, if a state agency elects to use a standard utility allowance, that allowance must be made available to HHs that received a payment under LEAP or another similar energy assistance program. Starting October 1, CDHS will issue EBT credits to HHs ($20 to help cover utilities + $1 for ATM fees) that didn't get LEAP in the prior 12 months. All eligible SNAP households will get this amount regardless of income, expenses, or HH size. The result is that all Colorado HHs will get the HCUA. The goal is to give HHs the highest possible utility deduction.
The rules will go into effect by August 1 with implementation October 1. Details are in this deck - https://docs.google.com/presentation/d/1LjJz-Ycx1-acefOcEJNtMxVRGfYMLEQgbRxGtEeyYgI/edit#slide=id.g2ab7e3e92af_0_134.

**Comment by MaxGhenis** [comment] 2024-06-18 14:08
Duplicate of #4246

**Closed by MaxGhenis** 2024-06-18 14:08 UTC
Labels: snap, states/co
